import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Navbar";
import Navbar from "./components/Navbar";
import BottomBar from "./components/BottomBar";
import TopToolsBar from "./components/TopToolsBar";
import PulseHeaderBar from "./components/PulseHeaderBar";
import ThreeColumnsBoard from "./components/ThreeColumnsBoard";
import { Import } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        <TopToolsBar/>
        <PulseHeaderBar />
        {/* <NewPairsSection /> */}
        <ThreeColumnsBoard />
        {/* <CryptoDashboardLucide/> */}
        <BottomBar/>
      </body>
    </html>
  );
}
